spring:
  application:
    name: Cp5-Java
  ai:
    openai:
      #Trocar a Key da OpenIA que não está funcionando
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o